"use client";
import { Inter } from "next/font/google";
import styled from "@emotion/styled";

const BodyCustom = styled.body`
  background-color: #171717;
  color: #fff;
  margin: 0;
  padding: 0;
`;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <BodyCustom className={inter.className}>{children}</BodyCustom>
    </html>
  );
}
